# Generated by Django 3.2.3 on 2021-05-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name_plural': 'Список Друзей'},
        ),
        migrations.AddField(
            model_name='friend',
            name='friend_icecream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friends', to='icecream.icecream', verbose_name='Любимые сорта мороженого'),
        ),
    ]
